name: Code Quality
on:
  pull_request:
    branches:
      - master
      - staging

concurrency:
  group: github-hosted-${{ github.head_ref || github.ref }}-${{ github.base_ref }}
  cancel-in-progress: true

jobs:
  testing:
    name: lint and test the package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up Node.js version
        uses: actions/setup-node@v6
        with:
          node-version: lts/Jod
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Check package integrty
        run: npm audit signatures

      - name: Lint the code
        run: npm run lint

      - name: Test the code
        run: npm run test
